sandbox_mode = "workspace-write"
approval_policy = "untrusted"
show_raw_agent_reasoning = true
model_verbosity = "low"
model_reasoning_summary = "detailed"

[sandbox_workspace_write]
network_access = true

[tools]
web_search = true

